name: Contract Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-contract:
    uses: hawthorne-abendsen/contract-build-workflow/.github/workflows/release.yml@master
    with:
      release_name: ${{ github.ref_name }}
      build_path: '[
          "contract2/nested", 
          "", 
          "contract"
        ]'
      release_description: 'Release of the contract'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}