name: Manual Contract Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name for the release'
        required: true
        type: string              

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release-contract-nested:
    uses: hawthorne-abendsen/contract-build-workflow/.github/workflows/release.yml@master
    with:
      release_name: ${{ github.event.inputs.release_name }}
      relative_path: "contract2/nested"
      package: "reflector-oracle-v2"
      release_description: 'Release of the nested contract'
      home_domain: "nested.org"
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}

  release-contract-root:
    uses: hawthorne-abendsen/contract-build-workflow/.github/workflows/release.yml@master
    with:
      release_name: ${{ github.event.inputs.release_name }}
      release_description: 'Release of the root contract'
      home_domain: "www.root.org"
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
  

  release-contract-contract:
    uses: hawthorne-abendsen/contract-build-workflow/.github/workflows/release.yml@master
    with:
      release_name: ${{ github.event.inputs.release_name }}
      relative_path: "contract"
      package: "reflector-oracle-v1"
      make_target: "test"
      release_description: 'Release of the /contract'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}