name: Rust

on:
  push:
    tags:
      - 'v*'

jobs:
  release-contract:
    uses: hawthorne-abendsen/contract-build-workflow/.github/workflows/create-contract-release.yml@master
    with:
      release_name: ${{ github.ref_name }}
      contract_dirs: '["contract"]'
      release_description: 'Release of the contract'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}