name: Rust

on:
  push:
    tags:
      - 'v*'

jobs:
  release-contract:
    uses: hawthorne-abendsen/contract-build-workflow@v0.5.0
    with:
      release_name: ${{ github.ref_name }}
      contract_dir: 'contract'
      release_description: 'Release of the contract'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}